### ISSUE TITLE
The Installation guide lacked scipy lib

### ISSUE THREAD

**Issue by ghost** [pth1993/vnSRL#1]
Hi team, thanks for sharing great project, i think installation guide should guide user install scipy lib.

i followed this installation guide, and got message:

`Running Vietnamese Semantic Role Labelling Toolkit
Loading Parameters
Traceback (most recent call last):
  File "vnSRL.py", line 30, in <module>
    leLabelFile)
  File "/Users/anhbientuan/vnSRL/lib.py", line 401, in readingParameterFromFile
    model = pickle.load(input)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
  File "/usr/local/lib/python2.7/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/usr/local/lib/python2.7/site-packages/sklearn/base.py", line 9, in <module>
    from scipy import sparse
ImportError: No module named scipy
`

in this error, it showed "No module named scipy", after i install scipy lib, everthing is fine. :)

**Comment by khoaipx** [comment]
Thank you for realizing our mistake! I updated User guide.
